using System.ComponentModel.DataAnnotations;
using System.Security.Permissions;

Console.WriteLine($"int:");
Console.WriteLine($"Size: {sizeof(int)} bytes");
Console.WriteLine($"Min: {int.MinValue}");
Console.WriteLine($"Max: {int.MaxValue}");
Console.WriteLine();
Console.WriteLine($"double:");
Console.WriteLine($"size: {sizeof(double)} bytes");
Console.WriteLine($"min:{double.MinValue}");
Console.WriteLine($"max: {double.MaxValue}");
Console.WriteLine();
Console.WriteLine($"sbyte:");
Console.WriteLine($"size: {sizeof(sbyte)} bytes");
Console.WriteLine($"min:{sbyte.MinValue}");
Console.WriteLine($"max:{sbyte.MaxValue}");
Console.WriteLine();
Console.WriteLine($"byte:");
Console.WriteLine($"size: {sizeof(byte)}byte");
Console.WriteLine($"min: {byte.MinValue}");
Console.WriteLine($"max: {byte.MaxValue}");
Console.WriteLine();
Console.WriteLine($"short:");
Console.WriteLine($"size: {sizeof(short)}byte");
Console.WriteLine($"min: {short.MinValue}");
Console.WriteLine($"mix: {short.MaxValue}");
Console.WriteLine();
Console.WriteLine($"ushort:");
Console.WriteLine($"size: {sizeof(ushort)}byte");
Console.WriteLine($"min: {ushort.MinValue}");
Console.WriteLine($"max: {ushort.MaxValue}");
Console.WriteLine();
Console.WriteLine($"uint:");
Console.WriteLine($"size: {sizeof(uint)}byte");
Console.WriteLine($"min: {uint.MinValue}");
Console.WriteLine($"max: {uint.MaxValue}");
Console.WriteLine();
Console.WriteLine($"long:");
Console.WriteLine($"size: {sizeof(long)}byte");
Console.WriteLine($"min: {long.MinValue}");
Console.WriteLine($"max: {long.MaxValue}");
Console.WriteLine();
Console.WriteLine($"ulong:");
Console.WriteLine($"size: {sizeof(ulong)}byte");
Console.WriteLine($"min: {ulong.MinValue}");
Console.WriteLine($"max: {ulong.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Int128:");
Console.WriteLine($"size: {System.Runtime.InteropServices.Marshal.SizeOf<Int128>()}byte");
Console.WriteLine($"min: {Int128.MinValue}");
Console.WriteLine($"max: {Int128.MaxValue}");
Console.WriteLine();
Console.WriteLine($"UInt128:");
Console.WriteLine($"size: {System.Runtime.InteropServices.Marshal.SizeOf<UInt128>()}byte");
Console.WriteLine($"min: {UInt128.MinValue}");
Console.WriteLine($"max: {UInt128.MaxValue}");
Console.WriteLine();
Console.WriteLine($"half:");
Console.WriteLine($"size: {System.Runtime.InteropServices.Marshal.SizeOf<Half>()}byte");
Console.WriteLine($"min: {Half.MinValue}");
Console.WriteLine($"max: {Half.MaxValue}");
Console.WriteLine();
Console.WriteLine($"float:");
Console.WriteLine($"size: {sizeof(float)}byte");
Console.WriteLine($"min: {float.MinValue}");
Console.WriteLine($"max: {float.MaxValue}");
Console.WriteLine();
Console.WriteLine($"decimal:");
Console.WriteLine($"size: {sizeof(decimal)}byte");
Console.WriteLine($"min: {decimal.MinValue}");
Console.WriteLine($"max: {decimal.MaxValue}");
Console.WriteLine();


